@tool
class_name LumenDocsIndex
extends RefCounted

## Compact Godot 4 class hints. Official docs remain the source of truth.

const ENTRIES := [
	{"name": "Node", "blurb": "Base of the scene tree. Groups, signals, process."},
	{"name": "Node2D", "blurb": "2D transform. Position, rotation, scale."},
	{"name": "Node3D", "blurb": "3D transform. Position, basis, visibility."},
	{"name": "Control", "blurb": "UI base. Anchors, size flags, theme, focus."},
	{"name": "CanvasItem", "blurb": "Draw and modulate 2D. Material, visibility."},
	{"name": "CharacterBody2D", "blurb": "Kinematic 2D body. move_and_slide, is_on_floor."},
	{"name": "CharacterBody3D", "blurb": "Kinematic 3D body. move_and_slide."},
	{"name": "RigidBody2D", "blurb": "2D physics body with mass and impulses."},
	{"name": "RigidBody3D", "blurb": "3D physics body with mass and impulses."},
	{"name": "StaticBody2D", "blurb": "Immovable 2D collider."},
	{"name": "Area2D", "blurb": "2D overlap and body entered signals."},
	{"name": "CollisionShape2D", "blurb": "Shape holder for 2D physics nodes."},
	{"name": "CollisionShape3D", "blurb": "Shape holder for 3D physics nodes."},
	{"name": "AnimatedSprite2D", "blurb": "Sprite frames animation."},
	{"name": "Sprite2D", "blurb": "Single texture sprite."},
	{"name": "TileMapLayer", "blurb": "Godot 4 tile layer. set_cell, get_used_cells."},
	{"name": "TileMap", "blurb": "Legacy multi-layer tilemap. Prefer TileMapLayer."},
	{"name": "AnimationPlayer", "blurb": "Named animation clips. play, queue."},
	{"name": "AnimationTree", "blurb": "Blend tree / state machine on an AnimationPlayer."},
	{"name": "Timer", "blurb": "One-shot or looping timeout signal."},
	{"name": "AudioStreamPlayer", "blurb": "Non-positional audio."},
	{"name": "AudioStreamPlayer2D", "blurb": "Positional 2D audio."},
	{"name": "Camera2D", "blurb": "2D view. Current, zoom, limits."},
	{"name": "Camera3D", "blurb": "3D view. Projection, current."},
	{"name": "RayCast2D", "blurb": "2D physics ray. is_colliding, get_collider."},
	{"name": "RayCast3D", "blurb": "3D physics ray."},
	{"name": "NavigationAgent2D", "blurb": "2D path follow helper."},
	{"name": "NavigationRegion2D", "blurb": "2D nav mesh region."},
	{"name": "GPUParticles2D", "blurb": "2D GPU particles."},
	{"name": "Label", "blurb": "Text control."},
	{"name": "Button", "blurb": "Clickable control. pressed signal."},
	{"name": "LineEdit", "blurb": "Single-line text input."},
	{"name": "TextEdit", "blurb": "Multi-line text input."},
	{"name": "RichTextLabel", "blurb": "BBCode text."},
	{"name": "TextureRect", "blurb": "UI texture."},
	{"name": "ColorRect", "blurb": "Solid color panel."},
	{"name": "Panel", "blurb": "Themed panel container."},
	{"name": "VBoxContainer", "blurb": "Vertical box."},
	{"name": "HBoxContainer", "blurb": "Horizontal box."},
	{"name": "MarginContainer", "blurb": "Padding container."},
	{"name": "ScrollContainer", "blurb": "Scrollable child."},
	{"name": "ItemList", "blurb": "Selectable list."},
	{"name": "OptionButton", "blurb": "Dropdown."},
	{"name": "ProgressBar", "blurb": "Value bar."},
	{"name": "Resource", "blurb": "Serialisable data. .tres / .res."},
	{"name": "Shader", "blurb": ".gdshader resource."},
	{"name": "ShaderMaterial", "blurb": "Material driven by a Shader."},
	{"name": "StandardMaterial3D", "blurb": "PBR 3D material."},
	{"name": "MeshInstance3D", "blurb": "Renders a Mesh."},
	{"name": "ArrayMesh", "blurb": "Procedural mesh."},
	{"name": "GridMap", "blurb": "3D tile grid."},
	{"name": "Input", "blurb": "Singleton. is_action_pressed, parse_input_event."},
	{"name": "InputMap", "blurb": "Action bindings."},
	{"name": "FileAccess", "blurb": "Read and write files."},
	{"name": "DirAccess", "blurb": "List and mutate directories."},
	{"name": "ProjectSettings", "blurb": "project.godot keys."},
	{"name": "SceneTree", "blurb": "Runtime tree. change_scene_to_file, create_timer."},
	{"name": "Tween", "blurb": "Property animation helper."},
	{"name": "HTTPRequest", "blurb": "Async HTTP."},
	{"name": "JSON", "blurb": "parse_string / stringify."},
	{"name": "GDScript", "blurb": "Script resource for .gd files."},
	{"name": "CSharpScript", "blurb": "Script resource for .cs files. Needs .NET build."},
]
